export const ARTICLE_PAGE_CONFIG = {
	meta: {
		titleSeparator: ' - ',
	},
	header: {
		backLabel: 'Blog',
		coverAriaLabel: '文章主图',
		metaAriaLabel: '文章信息',
		seriesAriaPrefix: '查看',
		seriesAriaSuffix: '系列',
		publishedLabel: '发布',
		updatedLabel: '更新',
	},
	toc: {
		minHeadingCount: 3,
		minDepth: 2,
		maxDepth: 4,
		title: 'On This Page',
		ariaLabel: '文章目录',
		behavior: {
			readingLineOffset: 72,
			bottomThreshold: 96,
			clickLockMs: 760,
			scrollSettleMs: 220,
			userIntentMs: 5000,
			inspectionLeaveMs: 1800,
			programmaticScrollMs: 720,
			revealCooldownMs: 160,
			revealAnchor: 0.3,
			revealMargin: 28,
			comfortTop: 0.24,
			comfortBottom: 0.68,
			comfortAnchor: 0.34,
			maxRevealStep: 96,
		},
	},
	series: {
		pageLabel: 'Series',
		sectionLabel: 'Series',
		fullSeriesPrefix: '查看完整系列',
		previousLabel: 'Previous',
		nextLabel: 'Next',
		emptyPrevious: '暂无更早的篇章',
		emptyNext: '暂无后续篇章',
	},
} as const;
